apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legacy-app-ingress
spec:
  rules:
  - host: legacy-app.example.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: legacy-app-service
            port:
              number: 80
